const HOMESCREEN="Home";
const EXPRESSSCREEN="Deals";
const FAVORITESSCREEN="Favorites";
const CARTSCREEN="Cart";
const PROFILESCREEN="Profile";

export {HOMESCREEN,EXPRESSSCREEN,FAVORITESSCREEN,CARTSCREEN,PROFILESCREEN}